# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hast}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Watson Steen"]
  s.date = %q{2010-02-17}
  s.default_executable = %q{hast}
  s.description = %q{      HAST stands for 'Hosting Account Status Tool'.

      HAST is a tool for fetching domains from Apache configuration files and
      from the Postfix database on a hosting server environment. It will then
      run a report, checking the DNS records for each domain to see if they
      match your server.

      This is important for finding "dead" domains where the domain either
      doesn't exist anymore or where the owner have moved it to another
      hosting provider.

      Before you can use HAST, you need to setup a config.yml file. Use
      config.yml.example as a template.
}
  s.email = %q{w@tson.dk}
  s.executables = ["hast"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/hast",
     "config.yml.example",
     "hast.gemspec",
     "lib/hast.rb",
     "lib/hast/apache.rb",
     "lib/hast/postfix.rb",
     "lib/hast/verifier.rb"
  ]
  s.homepage = %q{http://github.com/watson/hast}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Hosting Account Status Tool - Fetch domains from Apache configuration files and the Postfix database on a hosting server environment. Then run a report checking each domains DNS records to see if they match your server.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<mysql>, [">= 0"])
      s.add_development_dependency(%q<net-dns>, [">= 0"])
      s.add_development_dependency(%q<deep_merge>, [">= 0.1.0"])
    else
      s.add_dependency(%q<mysql>, [">= 0"])
      s.add_dependency(%q<net-dns>, [">= 0"])
      s.add_dependency(%q<deep_merge>, [">= 0.1.0"])
    end
  else
    s.add_dependency(%q<mysql>, [">= 0"])
    s.add_dependency(%q<net-dns>, [">= 0"])
    s.add_dependency(%q<deep_merge>, [">= 0.1.0"])
  end
end

